### ISSUE TITLE
Kolory są zbyt jednolite

### ISSUE THREAD

**Issue by kpucynski** [stepek/codi-lunch-stats#8]
Ostatnio kolory wykresów są tylko w odcieniach czerwono-fioletowo podobnych - nie da się ich rozróżnić.
Przydałoby się bardziej urozmaicić paletę :)

**Comment by stepek** [comment]
teraz lepiej?
http://codi-lunch-stats.herokuapp.com/

**Comment by kpucynski** [comment]
trochę lepiej. dziękuję!
